# Generated by Django 4.2.5 on 2023-09-20 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('img', models.ImageField(upload_to='ctg')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('img', models.ImageField(upload_to='products')),
                ('price', models.IntegerField()),
                ('desc', models.TextField()),
                ('ctg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.category')),
            ],
        ),
    ]
